## Data Cleanup and Manipulation
### Tohoku-Oki Earthquake - March 11, 2011

Article: https://www.nature.com/articles/ncomms13349

Website the data was on: https://www.eas.slu.edu/GGP/tohoku2011.html

Data used here is data recorded by a superconducting gravimeter in the underground Kamioka Observatory during the 2011 Mw 9.0 Tohoku-Oki earthquake in Kamioka, Japan. Latitude and Longitude are included in the file. Gravity is measured in (uGal) and pressure is measured in (hPa/V).

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Read in the data file
df = pd.read_table('ka110300.ggs', skiprows=list(range(0, 19)) + [20])

# Splitting the big column ['yyyymmdd hhmmss gravity(V) pressure(hPa)'] into new columns
df[['Date', 'Time', 'Gravity(uGal)', 'Pressure(hPa)']] = df['yyyymmdd hhmmss gravity(V) pressure(hPa)'].str.split(expand=True)

# Drop the old column
df.drop(columns=['yyyymmdd hhmmss gravity(V) pressure(hPa)'], inplace=True)

# Drop any values that are 'None' or blank
df = df.dropna()

       Date    Time Gravity(uGal) Pressure(hPa)
0  77777777  000000           0.0           0.0
1  20110301  000000      0.527852       968.549
2  20110301  000001      0.529700       968.547
3  20110301  000002      0.521487       968.547
4  20110301  000003      0.507439       968.549
5  20110301  000004      0.495192       968.552
6  20110301  000005      0.493443       968.552
7  20110301  000006      0.504535       968.552
8  20110301  000007      0.519782       968.556
9  20110301  000008      0.526215       968.559

In [3]:
df.head(10)

       Date    Time Gravity(uGal) Pressure(hPa)
0  77777777  000000           0.0           0.0
1  20110301  000000      0.527852       968.549
2  20110301  000001      0.529700       968.547
3  20110301  000002      0.521487       968.547
4  20110301  000003      0.507439       968.549
5  20110301  000004      0.495192       968.552
6  20110301  000005      0.493443       968.552
7  20110301  000006      0.504535       968.552
8  20110301  000007      0.519782       968.556
9  20110301  000008      0.526215       968.559

## Exploratory Visualizations

In [ ]:
# Plot 'Time' against 'Gravity(V)'
plt.figure(figsize=(10, 6))
plt.plot(df['Time'], df['Gravity(uGal)'], marker='o', linestyle='-')
plt.title('Time vs. Gravity')
plt.xlabel('Time')
plt.ylabel('Gravity(uGal)')
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()